#pragma once
#ifdef __INTELLISENSE__
#include <algorithm>
#include <concepts>
#include <fmt/core.h>
#include <functional>
#include <iostream>
#include <iterator>
#include <map>
#include <numeric>
#include <print>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <tuple>
#include <type_traits>
#include <typeinfo>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>
#else
import <algorithm>;
import <concepts>;
import <functional>;
import <iostream>;
import <iterator>;
import <map>;
import <numeric>;
import <print>;
import <queue>;
import <random>;
import <regex>;
import <set>;
import <sstream>;
import <stack>;
import <string>;
import <tuple>;
import <type_traits>;
import <typeinfo>;
import <unordered_map>;
import <utility>;
import <variant>;
import <vector>;
import <fmt/core.h>;
#endif
